# Generated by Django 2.1.7 on 2019-03-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='Date',
            new_name='date',
        ),
    ]
